# Your Solution
services:
  book_catalog:
    image: book_catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: catalog
    ports:
      - "8000:8000" 
    environment:
      - DATABASE_URL=postgresql://liki_db_user:OFEFAd6BVg24fFjz7VX3md0bYQOgVZmg@dpg-crldk5m8ii6s73d9j1s0-a.oregon-postgres.render.com/liki_db

  inventory_management:
    image: inventory
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://liki_db_user:OFEFAd6BVg24fFjz7VX3md0bYQOgVZmg@dpg-crldk5m8ii6s73d9j1s0-a.oregon-postgres.render.com/liki_db